services:
  smaiax-connector:
    image: smaiax-connector:latest
    container_name: smaiax-connector
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - smaiax-backend-network
    
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: "smaiax-backend-db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smaiax-db
    networks:
      - smaiax-backend-network

  rabbitmq:
    image: rabbitmq:4.0.2-management-alpine
    container_name: smaiax-mqtt-broker
    ports:
      - "1883:1883"  # MQTT port
      - "15672:15672"  # RabbitMQ Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_management rabbitmq_mqtt && rabbitmq-server"
    networks:
      - smaiax-backend-network
      
networks:
  smaiax-backend-network:
    name: "smaiax-backend-network"
    driver: bridge